### 1. Ottieni tutti i commenti di uno specifico post
GET http://localhost:5001/blogPosts/66d9e5cc857e56bd956864fc/comments
Content-Type: application/json

###

### 2. Ottieni un commento specifico di un post specifico
GET http://localhost:5001/blogPosts/{{postId}}/comments/{{commentId}}
Content-Type: application/json

###

### 3. Aggiungi un nuovo commento a un post specifico
POST http://localhost:5001/blogPosts/66d9e5cc857e56bd956864fc/comments
Content-Type: application/json

{
  "author": "Martina",
  "text": "Ho commentato vediamo se funziona!"
}

###

### 4. Modifica un commento specifico di un post specifico
PUT http://localhost:5001/blogPosts/{{postId}}/comments/{{commentId}}
Content-Type: application/json

{
  "content": "Commento modificato"
}

###

### 5. Elimina un commento specifico da un post specifico
DELETE http://localhost:5001/blogPosts/{{postId}}/comments/{{commentId}}
Content-Type: application/json

